name: verify

on: push

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up Python
        uses: actions/setup-python@v1

      - name: Install dependencies
        run: pip3 install -U online-judge-verify-helper

      - run: |
          mv src/atcoder ./
          rm -rf src
          mkdir -r .verify-helper/docs/static/
          rm -f document_ja/*.md
          mv document_ja .verify-helper/docs/static/

      # required only if you want to verify Nim code
      - name: Cache choosenim
        id: cache-choosenim
        uses: actions/cache@v1
        with:
          path: ~/.choosenim
          key: ${{ runner.os }}-choosenim-stable
      - name: Cache nimble
        id: cache-nimble
        uses: actions/cache@v1
        with:
          path: ~/.nimble
          key: ${{ runner.os }}-nimble-stable
      - uses: jiro4989/setup-nim-action@v1.1.3
        with:
          nim-version: 1.0.6

      - name: Run tests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          YUKICODER_TOKEN: ${{ secrets.YUKICODER_TOKEN }}
          GH_PAT: ${{ secrets.GH_PAT }}
        run: oj-verify all
